// 后端 decision_review_json 投影下发的 canonical 键集（抄自 fixture，非手猜）。
export const CANONICAL_KEYS = [
  "accountId",
  "approved",
  "autonomyProtocol",
  "contactWxid",
  "contextPackSnapshot",
  "createdAt",
  "domainConfigSnapshot",
  "finalReviewStatus",
  "formulaBreakdown",
  "holdCategory",
  "id",
  "inboundMessageId",
  "nextBestAction",
  "operationState",
  "outcomeStatus",
  "playbookId",
  "playbookVersion",
  "promptVersions",
  "reactionAnalysis",
  "replyText",
  "reviewSummary",
  "reviewPhase",
  "rewriteInstruction",
  "risks",
  "runId",
  "runtimeParametersSnapshot",
  "scores",
  "sendGatewayResult",
  "status",
  "usedKnowledgeIds",
  "workspaceId",
] as const;

export type CanonicalKey = (typeof CANONICAL_KEYS)[number];
