// 后端 outbox_entry_json 投影下发的 canonical 顶层键集(抄自 fixture,非手猜)。
export const CANONICAL_KEYS = [
  "accountId",
  "attempt",
  "cancelReason",
  "contactWxid",
  "content",
  "contentHash",
  "createdAt",
  "decisionId",
  "id",
  "idempotencyKey",
  "lastError",
  "lockedUntil",
  "maxAttempts",
  "nextRetryAt",
  "runId",
  "sentAt",
  "sourceEventId",
  "sourceKind",
  "status",
  "updatedAt",
  "workerId",
  "workspaceId",
] as const;
