// 后端 proposal_detail_json 投影下发的 canonical 顶层键集(抄自 fixture,非手猜)。
export const CANONICAL_KEYS = [
  "accountId",
  "cohortNotes",
  "createdAt",
  "criticReasoning",
  "currentValue",
  "diffSnippet",
  "diffSummary",
  "evalMetrics",
  "evalReplaysCompleted",
  "evalReplaysFailed",
  "expectedImprovementOn",
  "experimentId",
  "failureReason",
  "gateKey",
  "id",
  "kind",
  "previousPromptVersion",
  "proposedSection",
  "proposedTemplateKey",
  "proposedValue",
  "releasedAt",
  "releasedBy",
  "riskNote",
  "rolledBackAt",
  "rolledBackBy",
  "significancePassed",
  "status",
  "updatedAt",
  "workspaceId",
] as const;
